### PR TITLE
Add child routes to auto-generated(static) routes

### LINKED ISSUE #11: Does not see child page when generating the sitemap
Hi,

Thanks for this module.
I have an issue and do not know if it's a bug or not.

I have some children pages which are not dynamic:

Here is the list of url:
 
    /
    /singlePageA   
    /singlePageB
    /parentA/
    /parentA/childA
    /parentA/childB

Here is the folder set-up in the directory `pages`

    index.vue
    singlePageA.vue   
    singlePageB.vue
    parentA.vue
    parentA/
      index.vue    
      childA.vue
      childB.vue
   
Now if I run @nuxtjs/sitemap with the default value and just set `generate: true`, then only the following route are considered in the sitemap.xml:
    
    /
    /singlePageA   
    /singlePageB
    /parentA
    
Missing routes are:

    /parentA/    <--- Note the trailing forward slash
    /parentA/childA
    /parentA/childB

My understanding is that as those routes are "static" children routes, they should be considered by the `@nuxtjs/sitemap module`. Am I wrong?
Do I have to define them manually?
If so, do you a know an easy way to generate a route list (json file) and inject it in the `@nuxtjs/sitemap options`

Thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/sitemap-module/issues/c12">#c12</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by SnirShechter**
Up until now, the routes from vue-router were mapped to paths (routes.map(route => route.path). the route's children were ignored. this pull request recursively adds the children, building their respective route accordingly.

This fixes #11

### CODE REVIEW

**Comment by tomasbag** [comment]
Any progress on this?

**Comment by SnirShechter** [comment]
Any update on this?

We've started using the forked version because of this bug.

**Comment by manniL** [comment]
FYI: Had to reopen the PR to trigger CircleCI

**Comment by manniL** [comment]
@SnirShechter could you fix the failing CI?

**Comment by ameistad** [comment]
Any news on this? Really difficult to use the module with this bug.

**Comment by NicoPennec** [comment]
@SnirShechter Thank you for your proposal,
but I pushed a simpler one.

**Pull request closed without merging**
