### PR TITLE
Make translated static routes sitemaps

### PR DESCRIPTION
**Pull request by cwirz**
Waiting for the await import of the nuxt-i18n module initial extendRoutes call: https://github.com/nuxt-community/i18n-module/blob/22c38d7c122673e1c47066fe42e4ad1d81039b4b/src/core/hooks.js#L45

### CODE REVIEW

**Comment by andrewdego** [comment]
I found the same solution for the same problem. When will this PR be included in the master branch?

**Comment by rchl** [comment]
You don't need this anymore. Just update to latest `nuxt-i18n` version.

**Comment by andrewdego** [comment]
@rchl I tried with latest version (6.15.0) but I still have the problem. The sitemap urls are without the language prefix and no additional languages link generated

**Comment by rchl** [comment]
This change does two things:
 - handles Promise result from the previous module in the chain. This is no longer needed because `nuxt-i18n` is not returning Promise anymore. And also that bug was fixed in latest Nuxt (v2.14.5).
 - Calls `extendRoutes` from a hook so that it runs after the `nuxt-i18n` module. This is also no longer necessary because I've reverted to calling `extendRoutes` early in `nuxt-i18n`.

So with the latest version of i18n module, the order in which modules are declared is what decides which one extends routes first. Just making sure that `nuxt-i18n` module is registered before this module should make it work.

**Comment by andrewdego** [comment]
> This change does two things:
> 
> * handles Promise result from the previous module in the chain. This is no longer needed because `nuxt-i18n` is not returning Promise anymore. And also that bug was fixed in latest Nuxt (v2.14.5).
> * Calls `extendRoutes` from a hook so that it runs after the `nuxt-i18n` module. This is also no longer necessary because I've reverted to calling `extendRoutes` early in `nuxt-i18n`.
> 
> So with the latest version of i18n module, the order in which modules are declared is what decides which one extends routes first. Just making sure that `nuxt-i18n` module is registered before this module should make it work.

Thank you @rchl. I think my problem was due the old Nuxt version (v2.12). I upgraded it and now it works as expected.

**Comment by NicoPennec** [comment]
fixed on `nuxt-i18n` module

**Pull request closed without merging**
